---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.   
  - Сайт должен иметь мобильную версию.    
  - Сайт должен быть способен обрабатывать большое количество трафика    
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах

  
implicit:
  - В корзине сделать +/- количества товара (Что бы прибавить количество, нужно заходить на станицу товара).
  - В выборе категории товара добавить раздел "Все"(Что бы открыть заного "Все" нужно либо перезагрузить страницу, либо зайти в корзину и выйти).
  - Сделать панель навигации сайта (Поиск, категории, корзина, языки и Магазин вывести на Hexlet Store).
  - Снизу страницы сделать кнопку "Вернуться наверх" или плавающая панель навигации.
 
    
